blog:
  sessionInvalidateTime: 1800
  
server:
  tomcat:
    uri-encoding: UTF-8
  
spring:
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: fastjson
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代
  devtools:
    restart:
      exclude: static/**,public/**
    
mybatis: 
  mapperLocations: mapping/*.xml
  typeAliasesPackage: com.linsu.modular.*.model
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
